@startuml Final

class UsuarioLogin {
    -Nombre: String
    -Contraseña: String
    
    +Logueo(): void
    +CerrarSesion(): void

}

class Administrador {
    -Id: int

    +GestionarClub(): void
    +GestionarJugador(): void
    +GestionarFixture(): void
    +SubirBoletin(): void
    +GestionarSanción(): void
    +ResultadoPartido(): void
    +GestionarPartidos(): void

}


class Club {
    -NombrePresidente: String
    -NombreEntrenador: String
    -NombresJugadores: String
    -Categoria: String

    +VerFixture(): void
    +SuberCarnet(): void
    +AccederCarnetOtroEquipo(): void
    +ImprimirFormulario(): void
    +VerBoletin(): void
}


class Jugador {
    -Nombre: String
    -Apellido: String
    -Cedula: String
    -FechaNacimiento: Date
    
    +RecuentoTarjetas(): int  
}

class Partido {
    -FechaPartido: Date
    -HorarioPartido: String
    -DuracionPartido: String
    -ClubLocal: String
    -ClubVisitante: String
    -NombreEstadio: String
    -NombreArbitro: String
}

class Sancion {
    -TipoSancion: String
    -Motivo: String
    -CantidadFechas: int
}

class CarnetAptitud {
    -Vigente: Boolean
    -FechaVencimiento: Date
    -CarnetJugador: String
}

@enduml